#if defined _de_consts_included
	#endinput
#endif
#define _de_consts_included
/* ====================
*
*				常量
*
==================== */
#define Game_Description "[魔王 v1.0]"

//人物
#define CHARACTER_NAME_NONE "无"
#define CHARACTER_NAME_BILLY "比利海灵顿"
#define CHARACTER_NAME_BRS "黑岩射手"
#define CHARACTER_NAME_EZIO "艾吉奥"
#define CHARACTER_NAME_MCDONALD "蓝蓝路"

#define CHARACTER_INFO_BILLY "\y新日暮里的王 \r[+%.2f速 & %dHP]"
#define CHARACTER_INFO_BRS	"\y使用巨炮的少女\r[+%.2f%%伤害]"
#define CHARACTER_INFO_EZIO "\y强大的刺客\r[+%.2f%%奖励]"
#define CHARACTER_INFO_MCDONALD "\y麦当劳的守护者\r[+%.2f速]"

new const CAREER_NAME[][] =  {"游民",  "战士", "猎魔人", "法师",	 "圣骑士"}
new const CAREER_INFO[][] =  {"战五渣", "皮糙肉厚", "敏捷而致命", "吃我大火球啦", "奶飞天"}